apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
  labels:
    app: simple-time-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
      - name: simple-time-service
        image: tnikhilkumar/simple-time-service:latest 
        ports:
        - containerPort: 5000
