apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
  labels:
    app: simple-time-service
spec:
  type: LoadBalancer
  selector:
    app: simple-time-service
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
